# Generated by Django 4.1.5 on 2023-02-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="sal",
            field=models.CharField(max_length=50),
        ),
    ]
